### ISSUE TITLE
关于前3章的一些小建议

### ISSUE THREAD

**Issue by LeonardNJU** [datawhalechina/wonderful-sql#12]
### 第0章环境搭建，提供三个OS的教程（但没有ubuntu的）

centOS中讲的可能显得复杂了（？），实际上Ubuntu安装只用去[[MySQL :: Download MySQL APT Repository](https://dev.mysql.com/downloads/repo/apt/)](https://dev.mysql.com/downloads/repo/apt/)下载一个deb包，安装后`apt update`，然后`apt install mysql-server mysql-client libmysqlclient-dev`就能安装，途中配置按着来就行。

也没有初始随机密码，修改密码策略这些事（我没用密码123456这么简单的，哪怕是练习，要不然可能那天就真忘了上线了个弱口令DB）
各图形化数据库软件明显偏windows一些，介绍界面也以Windows的为主

### 第1章讲sql基本操作

内容不错，不过组织逻辑不是特别清晰。
比方说之前似乎没说查看表要先use <database_name>;select \* from <table_name>，以及show databases;show tables;可以查看有哪些表，这样萌新想看看自己修改的结果可能就看不了（？
设置默认值可在插入/修改时写DAFAULT，就像写NULL一样，这里没有给出示例代码

### 第2章讲查询

关于DISTINCT这里讲的有歧义。select distinct col from <table>是从table中显示col列中不同的值，不会删除重复的值（或者说，他只是把重复值再给你这次展示时折叠起来了）

2.5.2标点缺失，在给出常见错误原因后没加冒号。
2.5.2.1不一定得是聚合键，也可是其他列名的聚合函数

### 第3章是复杂查询
建议补充一下
`show tables;`会展示表和视图，而`show table status where comment='view';`或者
`select * from information_schema.views;`可以只展示视图。
多表视图就给了段代码意会，还没怎么具体讲规则（

**Comment by mba1398** [comment]
**第0章环境搭建**
1、已新增 Ubuntu MySQL 安装步骤
2、本教程侧重于引导学习者学会使用sql进行一些数据库操作，密码故意设置为123456，因为对于小白来说，忘记密码很常见，但是，处理这个问题却很棘手，超过 50% 的学习者会放弃学习sql。

**第1章讲sql基本操作**
已优化

**第2章讲查询**
除【2.5.2.1不一定得是聚合键，也可是其他列名的聚合函数】不敢苟同外，其他已优化。

**第3章是复杂查询**
已优化。
