### ISSUE TITLE
第4章内容是转载的吗

### ISSUE THREAD

**Issue by LeonardNJU** [datawhalechina/wonderful-sql#13]
看到了篇极其雷同的知乎文章：
https://zhuanlan.zhihu.com/p/521088110
以及
https://zhuanlan.zhihu.com/p/521476704
文字，内容，图片几乎一模一样，Ch04是转载的吗？是的话也许加个转载声明与原作者会比较好（？）

另外，MySQL 8.0 最新小版本（8.0.31）支持标准SQL 的intersect（交集）和except（差集）操作了，这个也许可以更新一下。

**Comment by mba1398** [comment]
经核实，ch04被知乎用户 `轩辕龙泽` 全文转载，但是该知乎用户未添加转载声明。
第二个问题，我们核实后进行更新。

**Comment by mba1398** [comment]
经核实，ch04被知乎用户 轩辕龙泽 全文转载，但是该知乎用户未添加转载声明。
第二个问题，我们核实后进行更新。
