### ISSUE TITLE
关于克隆仓库时报错的问题

### ISSUE THREAD

**Issue by xu-kai-xu** [datawhalechina/wonderful-sql#4]
克隆仓库时发现根目录下几个 `ch00 : ` 开头的文件目录非法，导致克隆失败。
但是下载压缩包时得到的对应的文件为 `ch00_` 格式的内容。
所以搞不清楚为啥github仓库中的文件名字还没有更改过来。

**Comment by mba1398** [comment]
可能是因为中文字符  ch00: 环境搭建.md，下载zip使用吧
