### ISSUE TITLE
ch03教程sql语句勘误

### ISSUE THREAD

**Issue by pache-Ak** [datawhalechina/wonderful-sql#5]
ch03 中 教程语句中 `productsum` 与 `productSum` 大小写不一致。

`productsum` 出现在第 62、 78、 164、 186、192、 196、 252 行；

`productSum` 出现在第 153、 156、162、 183、190、214、 217、255 行。

请修改。

**Comment by pache-Ak** [comment]
496行 `AS` 前后没有空格

**Comment by pache-Ak** [comment]
496行 `AS` 前后没有空格

**Comment by mba1398** [comment]
感谢反馈，我将尽快核实修正。
