### ISSUE TITLE
ch02,2.7.3小节

### ISSUE THREAD

**Issue by liuusummer** [datawhalechina/wonderful-sql#7]
你好，
2.7.3小节中，
“这是因为 SQL 在使用 HAVING 子句时 SELECT 语句的执行顺序为：

FROM → WHERE → GROUP BY → SELECT → HAVING → ORDER BY”
这里顺序是不是有点问题，应该是HAVING->SELECT吗

**Comment by mba1398** [comment]
HAVING 是对 SELECT 查询字段的过滤，所以需要先进行 SELECT。
